### ISSUE TITLE
new Request in V2 is not including base_url, causes all requests to fail

### ISSUE THREAD

**Issue by brynnb** [crucialwebstudio/chargify-sdk-php#10]
https://github.com/chargely/chargify-sdk-php/blob/master/src/Crucial/Service/ChargifyV2.php#L198

This causes a `"error" => "Could not resolve host: calls"` because it is attempting to make a request to `"url" => "HTTP://calls/01200a96bbe01fbc5177abd3396e2caae9d4d0f2"`. I assume there is something about the version of Guzzle you updated to that does not read the `base_url` as expected [when you create a new httpClient](https://github.com/chargely/chargify-sdk-php/blob/master/src/Crucial/Service/ChargifyV2.php#L99)

**Comment by brynnb** [comment]
Found the issue, `base_url` needs to be changed to `base_uri` as per [this upgrade guide](https://github.com/guzzle/guzzle/blob/5c12b74e9405c50fb0fd6ab831dd6e9df5560b1f/UPGRADING.md#L155):

`The base_url option has been renamed to base_uri.`

Looks like it was already fixed in the V1 service, just forgotten in V2 one.

**Comment by dan-bowen** [comment]
Thanks for the bug report. This has been fixed in `0.1.1`
