### ISSUE TITLE
Any reason why Guzzle version is hard coded?

### ISSUE THREAD

**Issue by petersuhm** [crucialwebstudio/chargify-sdk-php#16]
Just noticed that the Guzzle version for your SDK is hard coded, which means I can't use it with the AWS SDK...

Any specific reasons for this?

Thanks,

**Comment by dan-bowen** [comment]
Hello,

We like to lock down dependencies to specific versions to protect from inadvertently introducing bugs when the upstream dependency introduces a backwards incompatible change. If the upstream dependency correctly follows semver then this shouldn't be a problem but I have definitely seen other projects claim to follow semver yet introduce backwards incompatible changes with a point release. It really depends on the quality of the upstream project so we were very conservative with our approach.

I realize the hard-coded Guzzle version has been a problem for some users so it has been removed with release `0.1.2`. Our `composer.json` has been updated to `"guzzlehttp/guzzle": "^6.0"` so you should now be able to use any point release of Guzzle 6 in your project.
