### ISSUE TITLE
cancelImmediately results in error 500

### ISSUE THREAD

**Issue by tomw1808** [crucialwebstudio/chargify-sdk-php#20]
When I'm trying to cancel a subscription immediately, it results in an error 500 from chargify. 

Reproduce:

$chargify = new Chargify($arrConfig);
$subscription = $chargify->subscription();
$subscription->cancelImmediately(1234);

Possible cause:

An empty array is sent along as rawData.

Proposed Fix:

Service\Chargify\Subscription.php Line 437:

        $rawData = null;
        if($this->_params != []) {
            $rawData = $this->getRawData(array('subscription' => $this->_params));
        }

**Comment by AntoineLemaire** [comment]
I up this issue. @tomw1808's fix is working well

@crucialwebstudio, could you have a look?

Thanks

**Comment by dan-bowen** [comment]
Thanks for reporting and fixing this issue.

I have tagged a new release `v0.1.4` with the changes to fix this issue.
