### ISSUE TITLE
Network error

### ISSUE THREAD

**Issue by ghost** [crucialwebstudio/chargify-sdk-php#26]
No matter what I do or try, I keep getting the same error. I have developed everything on a staging server and it works fine. When i move it to our production servers we get the error below. No matter what call I make (subscriptions, transactions, ...) nothing works on server A while on server B the exact same script works fine. I have checked everything again and again but I must overlook something obvious.

The error we are getting in the response is : 

 { ["Crucial_Service_Chargify"]=> array(1) { ["networking error"]=> string(11) "no response" } }

**Comment by dan-bowen** [comment]
The fact that it works on staging seems to indicate a problem on the production server, not the library. I would verify your service can make outbound https requests and double check your chargify credentials.

**Comment by ghost** [comment]
Credentials are OK, since I just copy paste the script from one server to another and on 1 server they work, the other they dont.

I also agree it certainly is not a problem with the library. It has got to be something server-side on pur end, but I've spent almost 10 hours looking at the issue and not finding any solution. That's why I wanted to reach out here.

I will keep investigating .... any other suggestions are very very welcome

**Comment by ghost** [comment]
I found the issue. As I thought, something obvious that was overlooked.
I didn't load my CACERT in PHP.

I added some debugging to the Guzzle request and in between others I found the array "SSL : Unable to get local issuer" which got me triggered.

Loaded the CACERT.PEM in my php configuration and the request went through without a problem.

Hopefully others can benefit from this solution.

**Comment by dan-bowen** [comment]
Thanks for posting what you found.
