### ISSUE TITLE
Guzzle Version

### ISSUE THREAD

**Issue by julesbravo** [crucialwebstudio/chargify-sdk-php#5]
Using a very old version of guzzle that conflicts with all sorts of other dependencies.

**Comment by zillarelli** [comment]
+1 would be great if this could be updated

**Comment by morales2k** [comment]
+1

It makes it impossible to use the more recent guzzlehttp versions.

**Comment by dan-bowen** [comment]
We have started the upgrade to Guzzle 6. I will update this thread when it is complete.

**Comment by brynnb** [comment]
@crucialwebstudio Thanks a bunch!

**Comment by dan-bowen** [comment]
For everyone interested I just tagged version 0.1.0 which uses Guzzle 6. All the tests are passing but please let me know if you have any problems by opening a new issue.
